"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import os
import shutil
from setuptools import setup

# Ensure clean build
if os.path.exists("dist"):
    os.system('rm -rf dist')

if os.path.exists("build"):
    shutil.rmtree("build")

APP = ['notebook.py']

excludes=['alabaster', 
           'babel',
           'certifi',
           'cryptography',
           'docutils',
           'gevent',
           'Include',
           'IPython',
           'jedi',
           'jsonschemea',
           'lib2to3',
           'lxml',
           'markupsafe',
           'PIL',
           'psutil',
           'PyQt5', 
           'sphinx',
           'sqlalchemy',
           'tornado',
           'win32com',
           'zmq',
           ]
 
includes = ['wx.lib.pubsub']

OPTIONS = {
    'py2app': {
        'iconfile' : 'icon.icns',
        'argv_emulation' : False,
        'excludes': excludes,
        }
    }

DATA_FILES = ['splash.png']

setup(
    name='EPL ABR Analysis',
    version='1.5.2',
    app=APP,
    data_files=DATA_FILES,
    options=OPTIONS,
    setup_requires=['py2app'],
)
